# HISTORICAL: built MAESTRO-derived corpora on the 2026 GPU box (/root/datasets paths). MAESTRO v3 and
# those corpora are not part of this repository (see DATA.md, known missing); defaults are the box paths.
"""Build PAIRED distillation data: (real MAESTRO performance MIDI -> released-model pseudo score).

This is the corrected setup for teaching OFFSET PLACEMENT (which is only learnable from PAIRED
real-timing data, not the masked-timing unpaired SSL branch). The pseudo scores were generated by
the released model (the best tuplet-placer), so each pair distills its placement behaviour from the
SAME real MAESTRO timing.

Alignment-free: PDMXDataset's seq2seq does NOT need per-note MIDI<->score alignment (cross-attention
learns it), so for pieces that fit in one sequence we emit a single whole-piece chunk. We therefore
FILTER to pairs where both the MIDI and the score have <= seq_length notes (so the single chunk is
the complete, corresponding piece on both sides).

Out: pairs_maestro_paired/<id>.mid (symlink), <id>.musicxml (symlink), <id>_chunks.json (single chunk),
     + manifest CSV (id, midi, mxl, chunks, n_in_tokens, n_out_tokens).
"""
import argparse, glob, json, os, re, sys
from pathlib import Path
sys.path.insert(0, "/root/Music-ML-BayenLab/MIDI2ScoreTransformer/midi2scoretransformer")
import warnings; warnings.simplefilter("ignore")
import csv
from tokenizer import MultistreamTokenizer


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pseudo-dir", default="/root/datasets/maestro_pseudo")
    ap.add_argument("--maestro-root", default="/root/datasets/maestro-v3.0.0")
    ap.add_argument("--out-dir", default="/root/Music-ML-BayenLab/data/pairs_maestro_paired")
    ap.add_argument("--manifest", default="/root/Music-ML-BayenLab/data/pairs_maestro_paired_manifest.csv")
    ap.add_argument("--seq-length", type=int, default=512)
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    maestro = glob.glob(os.path.join(args.maestro_root, "*", "*.midi"))
    lut = {Path(m).stem[:60]: m for m in maestro}   # match pseudo filename's stem[:60]
    pseudo = sorted(glob.glob(os.path.join(args.pseudo_dir, "*.musicxml")))
    print(f"{len(pseudo)} pseudo scores, {len(maestro)} MAESTRO midis", flush=True)

    rows = []; kept = skipped_nomatch = skipped_toolong = failed = 0
    for ps in pseudo:
        stem = re.sub(r"^\d+_\d+_", "", Path(ps).stem)   # strip {shard}_{i}_
        midi = lut.get(stem)
        if midi is None:
            skipped_nomatch += 1; continue
        try:
            n_in = MultistreamTokenizer.parse_midi(midi)["pitch"].shape[0]
            n_out = MultistreamTokenizer.parse_mxl(ps)["offset"].shape[0]
        except Exception as e:
            failed += 1
            if failed <= 5: print(f"  parse fail {Path(ps).name[:40]}: {repr(e)[:70]}", flush=True)
            continue
        if n_in == 0 or n_out == 0 or n_in > args.seq_length or n_out > args.seq_length:
            skipped_toolong += 1; continue
        pid = f"mp{kept:04d}"
        mid_dst = os.path.join(args.out_dir, f"{pid}.mid")
        mxl_dst = os.path.join(args.out_dir, f"{pid}.musicxml")
        chunks_dst = os.path.join(args.out_dir, f"{pid}_chunks.json")
        for dst in (mid_dst, mxl_dst):
            if os.path.lexists(dst): os.remove(dst)
        os.symlink(midi, mid_dst); os.symlink(ps, mxl_dst)
        json.dump({"midi": [list(range(n_in))], "mxl": [list(range(n_out))], "swapped": False},
                  open(chunks_dst, "w"))
        rows.append({"id": pid, "midi": mid_dst, "mxl": mxl_dst, "chunks": chunks_dst,
                     "n_in_tokens": n_in, "n_out_tokens": n_out})
        kept += 1
    with open(args.manifest, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["id", "midi", "mxl", "chunks", "n_in_tokens", "n_out_tokens"])
        w.writeheader(); w.writerows(rows)
    print(f"KEPT {kept} pairs | no-match {skipped_nomatch} | too-long(>{args.seq_length}) {skipped_toolong} | failed {failed}", flush=True)
    print(f"manifest: {args.manifest}", flush=True)


if __name__ == "__main__":
    main()
